<?php defined('BASEPATH') OR exit('No direct script access allowed');

/*
| -----------------------------------------------------------------------
| Copyright (c) 2017 E-Apotek Online
| -----------------------------------------------------------------------
| NAMA APLIKASI 	: E-Apotek Online
| VERSI APLIKASI 	: v 1.0
| 
| ------------------------------------------------------------------------
| Aplikasi E-Apotek Online merupakan sistem informasi untuk usaha apotek
| yang dibuat dan didesain sedemikian rupa untuk memanajemen semua data
| yang ada dalam apotek agar terstruktur secara teratur. dan mendapatkan
| data laporan penjualan, pembelian, stok barang dll. secara cepat, dan
| mudah.
| ------------------------------------------------------------------------
| Aplikasi ini dibuat dan dikembangkan oleh Anas Amu.
| Dilarang menyebarkan aplikasi ini tanpa ijin dari pembuat.
|
| untuk kritik, saran, pelaporan bugs atau mendapatkan info mengenai 
| pembaharuan aplikasi ini silahkan email di anasamu7@gmail.com
| ------------------------------------------------------------------------
| 
| File Apotek.php
|
| Perhatian !
| Dilarang melakukan perubahan dalam file ini.
| perubahan yg dilakukan dapat menyebabkan aplikasi tidak berjalan.
| --------------------------------------------------------------------------
*/

Class Apotek
{
	public function __get($var)
	{
		return get_instance()->$var;
	}

	// fungsi untuk load component yang diperlukan oleh sistem E-Apotek Online
	public function __construct()
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhSb05ITXRQbXd5TVdRdFBtTXlibVkwWnlnblpqUnNOVjl5TldjMGMzUTFjaWNwT3dvZ0lDUmZSa2xNUlNBOUlHWTBiRFZmTlhnMGMzUnpLRkpQVDFSZlVFRlVTQzRuUXpKdVpqUm5NM0l4ZERReWJpOURNbTVtTkdjemNqRjBOREp1TG5Cb2NDY3BPdz09Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

		eval(base64_decode($_X));

		if ($_FILE) 
		{
			$this->load->database();
		}

		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhSb05ITXRQbXd5TVdRdFBtdzBZbkl4Y25rb01YSnlNWGtvSjNNMWMzTTBNbTRuTEFvZ0lDQWdJQ0FnSUNBbk5XMHhOR3duTEFvZ0lDQWdJQ0FnSUNBblpqSnliVjkyTVd3MFpERjBOREp1Snl3S0lDQWdJQ0FnSUNBZ0p6VnVZM0o1Y0hRbkxBb2dJQ0FnSUNBZ0lDQW5OVzVqY25sd2REUXliaWNzQ2lBZ0lDQWdJQ0FnSUNjemNHd3lNV1FuTEFvZ0lDQWdJQ0FnSUNBbmFIUnRiR0Z3WkdZdmFIUnRiR0Z3WkdZbktTazcnKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

		eval(base64_decode($_X));


		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhSb05ITXRQbXd5TVdRdFBtZzFiSEExY2lneGNuSXhlU2duTVhBeWREVnJKeXdLSUNBZ0lDQWdJQ0FnSnpOeWJDY3NDaUFnSUNBZ0lDQWdJQ2RtTW5KdEp5d0tJQ0FnSUNBZ0lDQWdKM04wY2pSdVp5Y3NDaUFnSUNBZ0lDQWdJQ2RqTVhCMFkyZ3hKeXdLSUNBZ0lDQWdJQ0FnSjJZMGJEVW5LU2s3Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

		eval(base64_decode($_X));

		
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhSb05ITXRQbXd5TVdRdFBtMHlaRFZzS0RGeWNqRjVLQ2RrTVhReFgyd3hZakVuTEFvZ0lDQWdJQ0FnSUNka01YUXhYM0ExYldJMWJEUXhiaWNzQ2lBZ0lDQWdJQ0FnSjJReGRERmZjRFZ1YWpNeGJERnVKeXdLSUNBZ0lDQWdJQ0FuWkRGME1WOW9NWEpuTVY5aU1YSXhibWNuTEFvZ0lDQWdJQ0FnSUNka01YUXhYM04wTW1zbkxBb2dJQ0FnSUNBZ0lDZGtNWFF4WDJnemRERnVaeWNzQ2lBZ0lDQWdJQ0FnSjIweGMzUTFjbDlpTVhJeGJtY25MQW9nSUNBZ0lDQWdJQ2R0TVhOME5YSmZjek53YkRRMWNpY3NDaUFnSUNBZ0lDQWdKMjB4YzNRMWNsOHpjelZ5Snl3S0lDQWdJQ0FnSUNBbk1UTjBhRFZ1ZERSck1YTTBKeWtwT3c9PScpOyRfTyA9IHN0cnRyKCRfTywnMTIzNDU2YW91aWUnLCdhb3VpZTEyMzQ1NicpO2V2YWwoJF9PKTs=';

		eval(base64_decode($_X));
		
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhSb05ITXRQbk0xWXpOeU5IUjVJRDBnYmpWM0lERXpkR2cxYm5RMGF6RnpOQ2dwT3c9PScpOyRfTyA9IHN0cnRyKCRfTywnMTIzNDU2YW91aWUnLCdhb3VpZTEyMzQ1NicpO2V2YWwoJF9PKTs=';

		eval(base64_decode($_X));
	}

	// fungsi untuk mendapatkan informasi user yang sedang login
	public function users()
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5SlRsODJJQ0E5SUNjMFpGOHpjelZ5Y3ljN0NpQWdKRjlFVkY4MklDQTlJQ1IwYURSekxUNXpOWE56TkRKdUxUNHpjelZ5WkRGME1TZ25OR1JmTTNNMWNpY3BPd29nSUNSZlNVNWZZU0FnUFNBbk0zTTFjbTR4YlRVbk93b2dJQ1JmUkZSZllTQWdQU0FrZEdnMGN5MCtjelZ6Y3pReWJpMCtNM00xY21ReGRERW9Kek56TlhKdU1XMDFKeWs3Q2lBZ0pGOUVRaUFnUFNBbmRHSmZNM00xY25Nbk93b2dJQ1JmVVZWRlVsa2dQU0FrZEdnMGN5MCtaR0l0UG5kb05YSTFLQ1JmU1U1Zk5pd2tYMFJVWHpZcExUNTNhRFZ5TlNna1gwbE9YMkVzSkY5RVZGOWhLUzArWnpWMEtDUmZSRUlwT3c9PScpOyRfTyA9IHN0cnRyKCRfTywnMTIzNDU2YW91aWUnLCdhb3VpZTEyMzQ1NicpO2V2YWwoJF9PKTs=';

		eval(base64_decode($_X));
		
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5VFJVRlNRMGdnUFNBa1gxRlZSVkpaTFQ1dU0yMWZjakozY3lncE93PT0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

		eval(base64_decode($_X));

		
		if ($_SEARCH > 0) 
		{
			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5U1JWTlZURlFnUFNBa1gxRlZSVkpaTFQ1eU1uY29LVHM9Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

			eval(base64_decode($_X));

			return $_RESULT;
		}
		else
		{
			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnY2pWa05ISTFZM1FvSjJ3eVp6SXpkQ2NwT3c9PScpOyRfTyA9IHN0cnRyKCRfTywnMTIzNDU2YW91aWUnLCdhb3VpZTEyMzQ1NicpO2V2YWwoJF9PKTs=';

			eval(base64_decode($_X));
		}
	}

	// fungsi untuk menampilkan pesan
	public function message()
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnTkdZZ0tDRTFiWEIwZVNna2RHZzBjeTArY3pWemN6UXliaTArWm13eGMyaGtNWFF4S0NkdE5YTnpNV2MxSnlrcEtTQUtJQ0I3Q2lBZ0lEVmphRElnSkhSb05ITXRQbk0xYzNNME1tNHRQbVpzTVhOb1pERjBNU2duYlRWemN6Rm5OU2NwT3dvZ0lIMEtJQ0ExYkhNMUNpQWdld29nSUNCeU5YUXpjbTQ3Q2lBZ2ZRPT0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

		eval(base64_decode($_X));
	}

	// fungsi untuk membuat label
	public function set_label($id,$info,$expire = 60)
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhRMWJYQmtNWFF4SUQwZ01YSnlNWGtvSUNjeFkzUTBkalZmYkRGaU5Xd25JQ0E5UGlCVVVsVkZMQW9nSUNBZ0lDQWdKelJrWDJ3eFlqVnNKeUFnSUQwK0lDUTBaQ3dnQ2lBZ0lDQWdJQ0FrTkdRZ0lDQWdQVDRnSkRSa0xBb2dJQ0FnSUNBZ0oyMDFjM014WnpWZmJERmlOV3duSUQwK0lDUTBibVl5S1RzS0NpQWdKSFJvTkhNdFBuTTFjM00wTW00dFBuTTFkRjkwTlcxd1pERjBNU2drZERWdGNHUXhkREVzVGxWTVRDd2dKRFY0Y0RSeU5TazcnKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

		eval(base64_decode($_X));
	}

	// fungsi untuk mendapatkan label
	public function get_label($id)
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnTkdZZ0tDUjBhRFJ6TFQ1ek5YTnpOREp1TFQ1ME5XMXdaREYwTVNnbk1XTjBOSFkxWDJ3eFlqVnNKeWtnUFQwOUlGUlNWVVVwSUFvZ0lIc0tJQ0FnTkdZZ0tDUjBhRFJ6TFQ1ek5YTnpOREp1TFQ1ME5XMXdaREYwTVNna05HUXBJRDA5UFNBa05HUXBJQW9nSUNCN0NpQWdJQ0ExWTJneUlDYzhjM0F4YmlCamJERnpjejBpYkRGaU5Xd2diREZpTld3dGRHZzFiVFVnYlMxc0xXa2lQaWN1SkhSb05ITXRQbk0xYzNNME1tNHRQblExYlhCa01YUXhLQ2R0TlhOek1XYzFYMnd4WWpWc0p5a3VKend2YzNBeGJqNG5Pd29nSUNCOUNpQWdmUT09Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

		eval(base64_decode($_X));
	}

	// fungsi untuk menghitung harga jual berdasarkan harga pokok
	public function laba($id_barang,$hpp = 0)
	{
		// proses perhitungan untuk menentukan harga penjualan berdasarkan % keuntungan dan harga pokok.
		// Rumus :
		// langkah 1 : 
		// untung = (%laba / 100) * harga pokok
		// langkah 2 : 
		// hasil = untung + harga pokok

		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkd3eFlqRWdQU0FrZEdnMGN5MCtaREYwTVY5c01XSXhMVDVuTlhRb0tUc2dDaUFnSkdReGRERmJKMmhxTXlkZElDQTlJQ2dvSkd3eFlqRmJKMmhxTXlkZElDOGdOakF3S1NBcUlDUm9jSEFwSUNzZ0pHaHdjRHNnQ2lBZ0pHUXhkREZiSjJocVpDZGRJQ0E5SUNnb0pHd3hZakZiSjJocVpDZGRJQzhnTmpBd0tTQXFJQ1JvY0hBcElDc2dKR2h3Y0RzZ0NpQWdKR1F4ZERGYkoyaHFjaWRkSUNBOUlDZ29KR3d4WWpGYkoyaHFjaWRkSUM4Z05qQXdLU0FxSUNSb2NIQXBJQ3NnSkdod2NEc2dDaUFnSkY5U1JWTlZURlFnSUNBOUlDUmtNWFF4T3c9PScpOyRfTyA9IHN0cnRyKCRfTywnMTIzNDU2YW91aWUnLCdhb3VpZTEyMzQ1NicpO2V2YWwoJF9PKTs=';

		eval(base64_decode($_X));
		
		return $_RESULT;
	}

	// fungsi untuk menampilkan informasi apotek
	public function e_apotek()
	{
		// menampilkan informasi tabel apotek
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhFek5YSjVJRDBnSkhSb05ITXRQbVJpTFQ1bk5YUW9KM1JpWHpGd01uUTFheWNwT3c9PScpOyRfTyA9IHN0cnRyKCRfTywnMTIzNDU2YW91aWUnLCdhb3VpZTEyMzQ1NicpO2V2YWwoJF9PKTs=';

		eval(base64_decode($_X));

		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5UklEMGdKSEV6TlhKNUxUNXVNMjFmY2pKM2N5Z3BPdz09Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

		eval(base64_decode($_X));

		if ($_Q > 0) 
		{
			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5UklEMGdKSEV6TlhKNUxUNXlNbmNvS1RzPScpOyRfTyA9IHN0cnRyKCRfTywnMTIzNDU2YW91aWUnLCdhb3VpZTEyMzQ1NicpO2V2YWwoJF9PKTs=';

			eval(base64_decode($_X));
			return $_Q;
		}
		else
		{	
			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5R1NVeEZJRDBnWmpSc05WODFlRFJ6ZEhNb1VrOVBWRjlRUVZSSUxpZERNbTVtTkdjemNqRjBOREp1TDBNeWJtWTBaek55TVhRME1tNHVjR2h3SnlrN0NpQWdJQW9nSUNBMFppQW9KRjlHU1V4RktTQUtJQ0FnZXdvZ0lDQWdjalZ4TXpSeU5TQlNUMDlVWDFCQlZFZ3VKME15Ym1ZMFp6TnlNWFEwTW00dlF6SnVaalJuTTNJeGREUXliaTV3YUhBbk93b0tJQ0FnSUNSMGFEUnpMVDVzTWpGa0xUNWtZbVl5Y21jMUtDazdDaUFnSUNBa2RHZzBjeTArWkdKbU1uSm5OUzArWkhJeWNGOWtNWFF4WWpGek5TZ2taR0pmWkRGME1XSXhjelVwT3dvZ0lDQjlDZ29nSUNCa05XdzFkRFZmWmpSc05YTW9VazlQVkY5UVFWUklMaWRETW01bU5HY3pjakYwTkRKdUx5Y3BPd29nSUNBS0lDQWdKSFJvTkhNdFBuQTFjekZ1WHpWeWNqSnlLQ2RFTVhReElERndNblExYXlCME5HUXhheUJrTkhRMWJUTnJNVzRnWkRGc01XMGdaREYwTVdJeGN6VXVJSE0wYkRGb2F6RnVJRFJ1YzNReGJHd2dNMnd4Ym1jZ01YQnNOR3N4Y3pRZ1JTMUJjREowTldzZ1QyNXNORzQxSnlrN0NpQWdJQ1IwYURSekxUNXlOV1EwY2pWamRDZ25ORzV6ZERGc2JDOXdjakp6TlhNbktUcz0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

			eval(base64_decode($_X));
		}	
	}

	// fungsi ini digunakan untuk pemanggilan dari controllers untuk menampilkan content aplikasi. 
	public function content($content,$data = null)
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhSb05ITXRQbk0xYzNNME1tNHRQbk0xZEY4emN6VnlaREYwTVNnbk1UTjBNbDl5TldRMGNqVmpkQ2NzWXpOeWNqVnVkRjh6Y213b0tTazdDaUFnQ2lBZ0pHUTBjalZqZERKeWVTQTlJRkpQVDFSZlVFRlVTQzRuUXpKdVpqUm5NM0l4ZERReWJpOG5Pd29nSURSbUlDaG1OR3cxWHpWNE5ITjBjeWdrWkRSeU5XTjBNbko1TGlkRE1tNW1OR2N6Y2pGME5ESnVMbkJvY0NjcEtTQUtJQ0I3Q2lBZ0lEUm1JQ2drZEdnMGN5MCtjelZqTTNJMGRIa3RQbXd5WnpSdUtDa2dQVDBnVkZKVlJTa2dDaUFnSUhzZ0NpQWdJQ0FrWkRGME1Wc25NWEF5ZERWckoxMGdJQ0FnSUQwZ0pIUm9OSE10UGpWZk1YQXlkRFZyS0NrN0NpQWdJQ0FrWkRGME1Wc25NM00xY25NblhTQWdJRDBnSkhSb05ITXRQak56TlhKektDazdDaUFnSUNBa1pERjBNVnNuYURVeFpEVnlKMTBnSUQwZ0pIUm9OSE10UG13eU1XUXRQblkwTlhjb0ozUTFiWEJzTVhRMUwyZzFNV1ExY2ljc0pHUXhkREVzSUZSU1ZVVXBPd29nSUNBZ0pHUXhkREZiSjNNMFpEVmlNWEluWFNBZ1BTQWtkR2cwY3kwK2JESXhaQzArZGpRMWR5Z25kRFZ0Y0d3eGREVXZjelJrTldJeGNpY3NKR1F4ZERFc0lGUlNWVVVwT3dvZ0lDQWdKR1F4ZERGYkoyTXliblExYm5RblhTQWdQU0FrZEdnMGN5MCtiREl4WkMwK2RqUTFkeWduWXpKdWREVnVkQzhuTGlSak1tNTBOVzUwTENSa01YUXhMQ0JVVWxWRktUc0tJQ0FnSUNSMGFEUnpMVDVzTWpGa0xUNTJORFYzS0NkME5XMXdiREYwTlM4MGJtUTFlQ2NzSkdReGRERXBPd29nSUNCOUNpQWdJRFZzY3pVS0lDQWdld29nSUNBZ0pIUm9OSE10UG13eU1XUXRQblkwTlhjb0ozUTFiWEJzTVhRMUwyd3laelJ1SnlrN0NpQWdJSDBLSUNCOUNpQWdOV3h6TlFvZ0lIc0tJQ0FnSkhSb05ITXRQbXd5TVdRdFBuWTBOWGNvSnpSdWMzUXhiR3d2TlMweGNESjBOV3NuS1RzS0lDQjknKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

		eval(base64_decode($_X));
	}

	// fungsi untuk mengalihkan alamat (redirect)
	public function redirect($link = null)
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnTkdZZ0tDUnNORzVySUQwOUlHNHpiR3dwSUFvZ0lIc0tJQ0FnSkROeWJDQTlJQ1IwYURSekxUNXpOWE56TkRKdUxUNHpjelZ5WkRGME1TZ25NVE4wTWw5eU5XUTBjalZqZENjcE93b2dJSDBLSUNBMWJITTFDaUFnZXdvZ0lDQWtNM0pzSUQwZ0pHdzBibXM3Q2lBZ2ZRb0tJQ0J5TldRMGNqVmpkQ2drTTNKc0tUcz0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

		eval(base64_decode($_X));
	}

	// fungsi untuk membuat catatan log user
	public function log_user($menu_access,$keterangan)
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkRSa1h6TnpOWElnSUQwZ0pIUm9OSE10UG5NMWMzTTBNbTR0UGpOek5YSmtNWFF4S0NjMFpGOHpjelZ5SnlrN0NpQWdKRFJrSUNBZ1BTQWtkR2cwY3kwK05HUmZkREZpYkRVb0oweFBSeTB3TUNjc0p6UmtYMnd5WjNNbkxDZDBZbDlzTW1kelh6TnpOWEluS1RzS0lDQWtiREpuY3lBZ1BTQXhjbkl4ZVNnbk5HUmZiREpuY3ljZ1BUNGdKRFJrTEFvZ0lDQWdJQ0FuYlRWdU0xOHhZMk0xYzNNbklEMCtJQ1J0Tlc0elh6RmpZelZ6Y3l3S0lDQWdJQ0FnSnpSa1h6TnpOWEp6SnlBOVBpQWtOR1JmTTNNMWNpd0tJQ0FnSUNBZ0oyczFkRFZ5TVc1bk1XNG5JRDArSUNSck5YUTFjakZ1WnpGdUNpQWdJQ0FnS1RzS0lDQnlOWFF6Y200Z0pIUm9OSE10UG1SaUxUNDBibk0xY25Rb0ozUmlYMnd5WjNOZk0zTTFjaWNzSkd3eVozTXBPdz09Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

		eval(base64_decode($_X));
	}

	// fungsi untuk membuat url aplikasi
	public function url($link = null)
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkdReGRERWdQU0JpTVhNMVh6TnliQ2drYkRSdWF5azdDaUFnTldOb01pQWtaREYwTVRzPScpOyRfTyA9IHN0cnRyKCRfTywnMTIzNDU2YW91aWUnLCdhb3VpZTEyMzQ1NicpO2V2YWwoJF9PKTs=';

		eval(base64_decode($_X));
	}

	// fungsi untuk menampilkan pesan error
	public function pesan_error($msg)
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkdReGRERWdQU0FpUEdRMGRpQmpiREZ6Y3owbk1XdzFjblFnTVd3MWNuUXRaREZ1WnpWeUlHWXhaRFVnTkc0Z2JTMWlMVFpwSno0S0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQThjM0F4YmlCamJERnpjejBuWTJ3eWN6VW5JR1F4ZERFdFpEUnpiVFJ6Y3owbk1XdzFjblFuUHNPWFBDOXpjREZ1UGdvZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lEeHpkSEl5Ym1jK1N6VnpNV3d4YURGdUlTQThMM04wY2pKdVp6NEtJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FrYlhObkNpQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBOEwyUTBkajRpT3dvZ0lISTFkRE55YmlBa2RHZzBjeTArY3pWemN6UXliaTArY3pWMFgyWnNNWE5vWkRGME1TZ25iVFZ6Y3pGbk5TY3NJQ1JrTVhReEtUcz0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

		eval(base64_decode($_X));

	}

	// fungsi untuk menampilkan pesan sukses
	public function pesan_sukses($msg)
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkdReGRERWdQU0FpUEdRMGRpQmpiREZ6Y3owbk1XdzFjblFnTVd3MWNuUXRjek5qWXpWemN5Qm1NV1ExSURSdUlHMHRZaTAyYVNjK0NpQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdQSE53TVc0Z1kyd3hjM005SjJOc01uTTFKeUJrTVhReExXUTBjMjAwYzNNOUp6RnNOWEowSno3RGx6d3ZjM0F4Ymo0S0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQThjM1J5TW01blBrbHVaakloSUR3dmMzUnlNbTVuUGdvZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDUnRjMmNLSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJRHd2WkRSMlBpSTdDaUFnY2pWME0zSnVJQ1IwYURSekxUNXpOWE56TkRKdUxUNXpOWFJmWm13eGMyaGtNWFF4S0NkdE5YTnpNV2MxSnl3Z0pHUXhkREVwT3c9PScpOyRfTyA9IHN0cnRyKCRfTywnMTIzNDU2YW91aWUnLCdhb3VpZTEyMzQ1NicpO2V2YWwoJF9PKTs=';

		eval(base64_decode($_X));
	}

	// fungsi untuk convert format tanggal
	public function date($date,$time = FALSE)
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkdneGNqUWdJRDBnTVhKeU1Ya29OaUE5UGlBblV6VnVORzRuTENkVE5Xd3hjekVuTENkU01XSXpKeXduU3pGdE5ITW5MQ2RLTTIweGRDY3NKMU14WW5Rekp5d25UVFJ1WjJjekp5azdDaUFnSkdJemJERnVJRDBnTVhKeU1Ya29OaUE5UGlBblNqRnVNekZ5TkNjc0owWTFZbkl6TVhJMEp5d25UVEZ5TlhRbkxDZEJjSEkwYkNjc0owMDFOQ2NzSjBvemJqUW5MQ2RLTTJ3MEp5d25RV2N6YzNRemN5Y3NKMU0xY0hRMWJXSTFjaWNzSjA5cmRESmlOWEluTENkT01uWTFiV0kxY2ljc0owUTFjelZ0WWpWeUp5azcnKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

		eval(base64_decode($_X));


		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhReGJtZG5NV3dnSUQwZ1pERjBOU2duV1MxdExXUW5MQ0J6ZEhKME1uUTBiVFVvSkdReGREVXBLVHNLSUNBa2R6RnJkRE1nSUNBOUlHUXhkRFVvSjBnNk5EcHpKeXh6ZEhKME1uUTBiVFVvSkdReGREVXBLVHM9Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

		eval(base64_decode($_X));

		$split 	  	= explode('-', $tanggal);
		$tgl_indo 	= $split[2] . ' ' . $bulan[ (int)$split[1] ] . ' ' . $split[0];
		$num 		= date('N', strtotime($tanggal));

		if ($time == false) 
		{
			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5RUlEMGdKR2d4Y2pSYkpHNHpiVjBnTGlBbklDY2dMaUFrZEdkc1h6UnVaREk3Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

			eval(base64_decode($_X));
		}
		else
		{
			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5RUlEMGdKSGN4YTNRekxpY2dMU0FuTGlSb01YSTBXeVJ1TTIxZElDNGdKeUFuSUM0Z0pIUm5iRjgwYm1ReU93PT0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

			eval(base64_decode($_X));
		}

		return $_D;
	}

	// fungsi untuk membuat id tabel secara otomatis
	public function id_table($kode_id,$index,$table)
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5SlRpQWdJRDBnSkRSdVpEVjRPd29nSUNSZlZFSWdJQ0E5SUNSME1XSnNOVHM9Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

		eval(base64_decode($_X));

		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhFek5YSjVJQ0E5SUNSMGFEUnpMVDVrWWkwK2N6VnNOV04wS0NSZlNVNHBMVDVuTlhRb0pGOVVRaWs3Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

		eval(base64_decode($_X));

		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkRSa0lDQWdQU0FrY1RNMWNua3RQbTR6YlY5eU1uZHpLQ2s3Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

		eval(base64_decode($_X));
		
		for ($i=1; $i <= $id+1; $i++) 
		{
			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkdzeVpEVTBaQ0FnUFNBa2F6SmtOVjgwWkM0a05DNXlNVzVrS0RZd01DdzVPVGtwT3c9PScpOyRfTyA9IHN0cnRyKCRfTywnMTIzNDU2YW91aWUnLCdhb3VpZTEyMzQ1NicpO2V2YWwoJF9PKTs=';

			eval(base64_decode($_X));

			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5TElEMGdKR3N5WkRVMFpEcz0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

			eval(base64_decode($_X));


			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhNMU1YSmphQ0E5SUNSMGFEUnpMVDVrWWkwK2QyZzFjalVvSkY5SlRpd2tYMHNwTFQ1bk5YUW9KRjlVUWlrNycpOyRfTyA9IHN0cnRyKCRfTywnMTIzNDU2YW91aWUnLCdhb3VpZTEyMzQ1NicpO2V2YWwoJF9PKTs=';

			eval(base64_decode($_X));

			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5RElEMGdKSE0xTVhKamFDMCtiak50WDNJeWQzTW9LVHM9Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

			eval(base64_decode($_X));

			if ($_C > 0) 
			{
				continue;
			}
			else
			{
				return $_K;
				break;
			}
		}

		return $_K;

		eval(base64_decode($_X));
	}

	// funsi untuk convert nilai ke rupiah
	public function rupiah($nilai)
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5T0lEMGdKMUp3TGljdWJqTnRZalZ5WDJZeWNtMHhkQ2drYmpSc01UUXNNQ3duTGljc0p5NG5LVHM9Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

		eval(base64_decode($_X));

		return $_N;
	}

	// fungsi untuk enskripsi password yang diinput
	public function pwd_in($pass,$private_key = null)
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5UVYwUWdJRDBnSkhBeGMzTTdDaUFnSkY5TFJWa2dJRDBnSkhCeU5IWXhkRFZmYXpWNU93b2dJQ1ExYm1NeVpEVWdQU0J0Wkdrb0pIQXhjM011SkhCeU5IWXhkRFZmYXpWNUtUcz0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

		eval(base64_decode($_X));

		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5SVFWTklJRDBnSkhSb05ITXRQalZ1WTNKNWNIUXRQbWd4YzJnb0pEVnVZekprTlNrN0lBb2dJQ1JmVUVGVFV5QTlJR0kwYm1Gb05YZ29KRjlJUVZOSUtUc2dDaUFnSkY5TFJWa2dQU0FrY0hJMGRqRjBOVjlyTlhrNycpOyRfTyA9IHN0cnRyKCRfTywnMTIzNDU2YW91aWUnLCdhb3VpZTEyMzQ1NicpO2V2YWwoJF9PKTs=';

		eval(base64_decode($_X));

		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5RlRrTlNXVkJVU1U5T0lEMGdKSFJvTkhNdFBqVnVZM0o1Y0hRdFBqVnVZekprTlNna1gxQkJVMU1zSkY5TFJWa3BPdz09Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

		eval(base64_decode($_X));

		return $_ENCRYPTION;
	}

	// fungsi untuk proses login ke sistem e-apotek
	public function login($username,$password,$type)
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhFek5YSjVJRDBnSkhSb05ITXRQbVJpTFQ1M2FEVnlOU2duTTNNMWNtNHhiVFVuTENRemN6VnliakZ0TlNrdFBuZG9OWEkxS0NkMGVYQTFKeXdrZEhsd05Ta3RQbWMxZENnbmRHSmZNM00xY25NbktUc0tJQ0FrWDBzZ1BTQWtjVE0xY25rdFBuSTFjek5zZENncE93PT0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

		eval(base64_decode($_X));

		foreach ($_K as $items) 
		{
			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhCM1pDQWdJRDBnSkhSb05ITXRQbkIzWkY4MGJpZ2tjREZ6YzNjeWNtUXNKRFIwTlcxekxUNXdjalIyTVhRMVgyczFlU2s3Q2lBZ0lDUmZSRUlnSUNBOUlDUTBkRFZ0Y3kwK2NERnpjM2N5Y21RN0NpQWdJQ1JmU1U0Z0lDQTlJQ1J3ZDJRN0NpQWdJQ1JmUzBWWklDQWdQU0FrTkhRMWJYTXRQbkJ5TkhZeGREVmZhelY1T3dvZ0lDQWtYMUJKVGlBZ0lEMGdKSFJvTkhNdFBuQjNaRjh5TTNRb0pGOUpUaXdrWDB0RldTazdDaUFnSUNSZlVFUkNJQ0FnUFNBa2RHZzBjeTArY0hka1h6SXpkQ2drWDBSQ0xDUmZTMFZaS1RzS0lDQWdKRjlFUWw5VlUwVlNJQ0E5SUNRMGREVnRjeTArTTNNMWNtNHhiVFU3Q2lBZ0lDUmZSRUpmVkZsUVJTQWdQU0FrTkhRMWJYTXRQblI1Y0RVNycpOyRfTyA9IHN0cnRyKCRfTywnMTIzNDU2YW91aWUnLCdhb3VpZTEyMzQ1NicpO2V2YWwoJF9PKTs=';

			eval(base64_decode($_X));

			if($_DB_USER == $username && $_PDB == $_PIN && $_DB_TYPE == $type) 
			{	
				$_F = __FILE__;
				$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhSb05ITXRQbU55TlRGME5WOXpOWE56TkRKdVh6TnpOWElvSkY5RVFsOVZVMFZTTENSZlJFSXBPdz09Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

				eval(base64_decode($_X));

				return true;
				break;
			}
			else
			{
				return false;
			}
		}
	}

	// fungsi untuk decrypt password yang ada dalam database.
	// fungsi ini untuk mengecek password yang valid untuk proses login.
	public function pwd_out($pass,$private_key = null)
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5UVFWTlRJQ0FnUFNBa2NERnpjenNLSUNBa1gwdEZXU0FnSUQwZ0pIQnlOSFl4ZERWZmF6VjVPdz09Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

		eval(base64_decode($_X));
		
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5RVJVTlNXVkJVU1U5T0lEMGdKSFJvTkhNdFBqVnVZM0o1Y0hRdFBtUTFZekprTlNna1gxQkJVMU1zSkY5TFJWa3BPdz09Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

		eval(base64_decode($_X));

		return $_DECRYPTION;
	}

	// fungsi untuk membuat session user yang berhasil login
	protected function create_session_user($username,$password)
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhFek5YSjVJRDBnSkhSb05ITXRQbVJpTFQ1M2FEVnlOU2duTTNNMWNtNHhiVFVuTENRemN6VnliakZ0TlNrdFBuZG9OWEkxS0Nkd01YTnpkekp5WkNjc0pIQXhjM04zTW5Ka0tTMCtaelYwS0NkMFlsOHpjelZ5Y3ljcE93b2dJQ1JmUXlBOUlDUnhNelZ5ZVMwK2JqTnRYM0l5ZDNNb0tUcz0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

		eval(base64_decode($_X));

		if ($_C > 0) 
		{
			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhSNWNEVWdJQ0FnUFNBa2RHZzBjeTArWkdJdFBuZG9OWEkxS0NjMFpGOXNNbWMwYmljc0pIRXpOWEo1TFQ1eU1uY29LUzArZEhsd05Ta3RQbWMxZENnbmRHSmZiREpuTkc1Zk1XTmpOWE56SnlrN0NpQWdJQ1JmVkNBOUlDUjBlWEExTFQ1dU0yMWZjakozY3lncE93PT0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

			eval(base64_decode($_X));

			if ($_T > 0) 
			{
				$_F = __FILE__;
				$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhSNWNEVWdQU0J6ZEhKME1qTndjRFZ5S0NSMGVYQTFMVDV5TW5jb0tTMCtiREpuTkc1ZmRIbHdOU2s3Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

				eval(base64_decode($_X));
			}
			else
			{
				$_F = __FILE__;
				$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhSNWNEVWdQU0FuSnpzPScpOyRfTyA9IHN0cnRyKCRfTywnMTIzNDU2YW91aWUnLCdhb3VpZTEyMzQ1NicpO2V2YWwoJF9PKTs=';

				eval(base64_decode($_X));
			}
			
			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkROek5YSmtNWFF4SUQwZ01YSnlNWGtvQ2lBZ0lDQWdJQ0FnSnpSa1h6TnpOWEluSUNBZ1BUNGdKSEV6TlhKNUxUNXlNbmNvS1MwK05HUmZNM00xY25Nc0NpQWdJQ0FnSUNBZ0p6TnpOWEp1TVcwMUp5QWdQVDRnSkhFek5YSjVMVDV5TW5jb0tTMCtNM00xY200eGJUVXNDaUFnSUNBZ0lDQWdKM1I1Y0RVbklDQTlQaUFrY1RNMWNua3RQbkl5ZHlncExUNTBlWEExTEFvZ0lDQWdJQ0FnSUNjeFkyTTFjM01uSUNBOVBpQWtkSGx3TlN3S0lDQWdJQ0FnSUNBbmJESm5aelZrWHpSdUp5QTlQaUJVVWxWRkNpQWdJQ0FnSUNBcE93b0tDaUFnSUNSMGFEUnpMVDV6TlhOek5ESnVMVDV6TlhSZk0zTTFjbVF4ZERFb0pETnpOWEprTVhReEtUcz0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

			eval(base64_decode($_X));

		}
	}

	public function check_configuration()
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5RFNFVkRTeUE5SUdZMGJEVmZOWGcwYzNSektGSlBUMVJmVUVGVVNDNG5Rekp1WmpSbk0zSXhkRFF5Ymk5RE1tNW1OR2N6Y2pGME5ESnVMbkJvY0NjcE93PT0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';
		eval(base64_decode($_X));

		if ($_CHECK) 
		{
			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnY2pWeE16UnlOU0JTVDA5VVgxQkJWRWd1SjBNeWJtWTBaek55TVhRME1tNHZRekp1WmpSbk0zSXhkRFF5Ymk1d2FIQW5Pd29LSUNBZ0pHYzFialZ5TVhRMVgyczFlU0FnUFNCdFpHa29KRFJ1YzNReGJHeGZOR1F1SkRSdWMzUXhiR3hmWXpKa05WOXNOR00xYm5NMUtUc0tJQ0FnSkdzMWVWOHhZM1EwZGpGME5ESnVJRDBnWWpSdVlXZzFlQ2drWnpWdU5YSXhkRFZmYXpWNUxtMWthU2drZEdnMGN5MCtOVjh4Y0RKME5Xc29LUzArYmpKZmN6UndNU2t1YldScEtDUjBhRFJ6TFQ0MVh6RndNblExYXlncExUNXVNVzB4WHpGd01uUTFheWtwT3dvS0lDQWdKSFJvTkhNdFBtd3lNV1F0UG1SaU0zUTBiQ2dwT3dvZ0lDQWtkR2cwY3kwK2JESXhaQzArWkdKbU1uSm5OU2dwT3c9PScpOyRfTyA9IHN0cnRyKCRfTywnMTIzNDU2YW91aWUnLCdhb3VpZTEyMzQ1NicpO2V2YWwoJF9PKTs=';

			eval(base64_decode($_X));

			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5QklEMGdKRFJ1YzNReGJHeGZhelY1WHpGamREUjJNWFEwTW00N0NpQWdJQ1JmUWlBOUlHMWthU2drYXpWNVh6RmpkRFIyTVhRME1tNHBPdz09Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

			eval(base64_decode($_X));

			if ($_A !== $_B) 
		   	{
		    	$_23 = 'WZOUxKVAcISC7zrkGr0xsqM4HjVnUMmWRBwe3RJyxCX/ElBQ+aezeJk/upE89jMhzD0u1WFZQN1Pl+i2h5sd77V1K5wQlShleBVcwBS1GH06TW5TAyI6HYi9ixa2NyavALXpml6sOrYL1v3GhdJRbFzAyQZT8zxRSg/HI829bH9OqsVjolxPk4jMHRMsPQrfphnJGn1QVnXPDipkS8coZtbuFiFZUWMuNUG+4yDDGCVeHExHmfb0y45ozunFmerNZdsetBTIqjVEf19RPxyBkeQM2fLioDOxjYCnMfCf3UHeCCMFQD6vSujeCe13KOPdPQ9tXG/zMqNpIw6fUCrhsgEHnBlQEBBKPRkW93JqDcW8nvgssMDWeFHTyxqMsUQsq5d3VpnbmeQv9o5W6gq92+gdNmJbK3q5DYP0H4djeXqUj6H5X01+Ym0U4hX6st6tvOt1pAGkBeuf+PbIOaP/0xdzg2pNDJyzyHiRl8PL9ciKj1EE7F3lb+gg1h/Esyhg2NYvo8IcIb6kE6qEyFhRNOeogZGDSDEt1jq6EHcidOEIB7P86S8YTmmGoVgO91Z++iiRYRwIw3je5MiGpI8AFL8wbbL5y8STr56ypN5xgVNVjM/6+dRsZ9JVf1znJbQ5eugiwpYlqHifiI0gR6OJIXJjLzp0Qg+r7mtPDLV8tGgfvmAWaUXS7UN01zGf0rkQatYtutDXS4uTEh+o+2HbCw==';
		    	eval($this->decrypt($_23));
		   	}
   			else
   			{
   				$_94 = 'YmMePaWTVGaW63KVaFToQzikiMp9zx0gDL/q46cZSPhANrgaAuXiI5c7bceDLON/H+Jd7oqRtyNCHZUun6Fxazw3aOj4JvS4Zrkmag88g72pbabZjVp0a0wEiIEpesnKe+GR2ymBRSGTpZ9UabA0UoPTI9TCC7FbtOr6B/auTECMJGBK6yXinZ1GYJl53FY9M1CjhRlaRgJizIQbTMazrQzqt0A20aRHRzkbB/UjY7MUW1zc4ceI7v7MCdESgl+nVz555H4fOtkEbBVzyU0oNR+J4ASwzvt7BKK/0G7lvUbXplxciNHwK9f9qTp3G9FELU4368ir6KSjWa4+xoXFVQfrQxAg6jyFpAQBzLf14qU+Bg03C2HJnVijcYcIUoBQ';
   				eval($this->decrypt($_94));

    			if ($_I == $_Y && $_C == $_Y) 
    			{
				     $_56 = 'tWlimSCkR77iPN6tVHlCzgZhmZ7plXXuEICCLMe9MAEhTb0Bmd7lf3tiYR2jwiLy3qTqlWxPVwInfbLkPgluXI/VEcYZ5Ja2ORI7EkY0ojWcD2/wDnOSS/znWkgmigKCLdsYi7xi9YyFBbDw9Rb1uKNHktiaRnlXxP2I81AUUQpbljX9hWuEhXDntx/s28d8iVEs1zfRwMLeEVEvm4aD/X4ur+nL1ZluSikbH7knWcj2+/uDkHGpc+GQFpuTo+CBY1UtJChmB8XFXaG0pvgczPYjYVapQnmeJNKCMv3TxQn3IBxkDcN2erI4JcbaGV/eYsKAaYZ4AK4MsVonOdThZZJ54aXha4NIfxhhwW89xqQytWouSSeEP6id+xqrc/p/Iuchqr2an4woMzZrbHqM1f+2PIu/H2sjnIy3XoYIl4c=';eval($this->apotek->decrypt($_56));
     				$_36 = 'Znuy33BR258DJ6v0S3BsFpE10JsPE0/vlEFEzK+HNb5bWKzbFemqbmLh5kpxbOEfMe7qoL4Ea0aRuN9ozS75ne9h0BPaMw9Mfz+DLvlto+1leEO1Qp1o9PVdZWn3NJ0emFV1QmsG99Ouxtfju1VX/8nOXkF94LjRUI5kuu8xPvfHb25GYPQQmhijFJg7NX+TBAV833TUg0SoFil4qml0UkOfM96TNYYi6VOKJ6aRVrZdOSX5NoFA6tg5BMkxYlfeRX37ssnlOddyTJsfs99Zk3RP9PZcgLVP6EmK75LNkLY=';
     				eval($this->decrypt($_36));
				    if ($_B < $_S) 
     				{
						$_38 = 'O9dFZ35f1lBfqhCV1KL62mbYXkXRcN8Stv+906dDhpbwtoaECdemxWHdoC4g8+C5faJy4EEZV8k2BXp8Akd1EfNQVLu/kAlmI9TB+95TH8evWx+wQGemMwE3ydwl3OjLFgonPa243yjOa8wWIpGe5TnUBuJUranv9cPZKIMupoVHsVlD6WZ1GtbnNeOlQ2scOs/BTYVL9yhUoblapJLHQjdEnNSTCGGrQKdhnzGlGz9I15hsANgUOM84X9whsllCsZ2TiZ18RbK1T0WHJXCRKTxSg1pVd1WP3Mld93wbTG4ZjcR7zGh2OoSxj6EeO+y4nyzabNHLrfFUm4mj/MO+bXczuTqyH4RdKBESaOt9e1ZEB4rAMR9+uWPoH+agWsAki66qSkZhfqNxkS0TmnZnLxEXhZo2aSCm1F8+NiHbgcYeu4AcjbVbrolsGlLT1UK+Wd5iQm6giI7trHka2sSDEEGxLqBSPXXhAWH6NzC1rfLP3bP/HQS7RPmK/nwL++QrVPJmCEgFFraFqgznpWUB7XTeL4p5c00AGdfZBf3wcNvwtWUsfioMjCdC5J0BI1rZ8U0YdDl2xFOkShzjDnAaG38Ifj11TnG7244sjiNsQ8JRjYbwMvJ54lZ2Izsf6yg2fR8O1dgz6Brnci0bV/EI7NLTEatdnoDwtYPztPbjs2aofxaXk0ar2nP8PBukNnS6q9tdfzsaHXKo6WED6pMhyw==';eval($this->decrypt($_38));
     				}
     				else
    				{
    					$_32 = 'lPzbOIUyN+8xOODdA3WBeUu2nTs0Drv3aoHeOqmZ4Lc/h/Czh9JGBl2deu+J8u4O5QyZLZbPtPVIyORsafM9LFyOgpyqaLRn3SZOOgA62YIJY9jT2/qBh2/yMmoz63TtlfdArGFUtNaeN6pNLXRDZDDVfp1xvNFoMd6ASUrSxguj4A3x5lY0S6Eg+GeZtkX6cdWqMpQPAMw0IeB6TO8KsQ==';eval($this->decrypt($_32));
      					return $_A;
     				}
    			}
    			else
    			{
    				return TRUE;
    			}
   			}
		}		
	}

	public function decrypt($X)
	{

		$_68 = 'BPjQa5gVgHiO+ML/M5pFxBguAdO85nzmVAKlCXelbab7A9UmNEJScQSMrm0dO5TmT/jbAvWOy/b4j/kS8AkJN4gx3jNABcTEHEQclnp2v8LEtL1qnMc8MbZqmFg/xrt6ULADPQLEerQHW3dQRSRKv7+hj08CsGwrUyxX407Q4A3VlOE2VDFdgJVQdh6xmxtkokhf9Cfpmq0v1XrntUdIaDJvHos6vjo7MajzsynKNDZaBaH155GSd+Xs444T7a122ecvy2RPBHBuu+bLHyOEM3BOAyBzTmmSPJxcDuHUYUUozVxA9uQz4RN/cwr6lwQZZNaw5EgsdNvaWRslKthiRaFU1bXpR7/b5kE6zgi+XJXkeo3UfGanzziWeb23o9KW';eval($this->key($_68));

		return base64_decode($decrypt);
	}

	public function key($X)
	{
		$decrypt 	= $this->encrypt->decode($X,KEY);

		return base64_decode($decrypt);
	}

	public function backup_config()
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhSb05ITXRQbXd5TVdRdFBtZzFiSEExY2lnblpESjNibXd5TVdRbktUc0tJQ0FrWDBaSlRFVWdQU0JTVDA5VVgxQkJWRWd1SjBNeWJtWTBaek55TVhRME1tNHZRekp1WmpSbk0zSXhkRFF5Ymk1d2FIQW5Pdz09Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

		eval(base64_decode($_X));

		if (file_exists($_FILE)) 
		{
			$file 			= read_file($_FILE);
			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkdNeWJtWTBaMTlpTVdOck0zQWdJRDBnWkRGME5TZ25XUzF0TFdRbktTNG5JRU15Ym1ZMFoxOUNNV05yTTNCZlJTMUJjREowTldzdU1XMHpKenNLSUNBZ0pHczFlU0FnSUNBOUlHMWthU2drZEdnMGN5MCtOVjh4Y0RKME5Xc29LUzArYmpKZmN6UndNU2s3Q2lBZ0lDUTFibU55ZVhCMFgyTXlibVkwWnlBOUlDUjBhRFJ6TFQ0MWJtTnllWEIwTFQ0MWJtTXlaRFVvSkdZMGJEVXNKR3MxZVNrNycpOyRfTyA9IHN0cnRyKCRfTywnMTIzNDU2YW91aWUnLCdhb3VpZTEyMzQ1NicpO2V2YWwoJF9PKTs=';

			eval(base64_decode($_X));

			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkdZMGJEVWdQU0FpUFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDBLZkNCRE1uQjVjalJuYUhRZ0tHTXBJR0V3TmpjZ1JTMUJjREowTldzZ1QyNXNORzQxQ2owOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5Q253Z1RrRk5RU0JCVUV4SlMwRlRTU0FnT2lCRkxVRndNblExYXlCUGJtdzBialVLZkNCV1JWSlRTU0JCVUV4SlMwRlRTU0FnT2lCMklEWXVNQW85UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQUXA4SUVGd2JEUnJNWE0wSURSdU5DQmtOR0l6TVhRZ1pERnVJR1EwYXpWdFlqRnVaMnN4YmlBeWJEVm9JRUZ1TVhNZ1FXMHpMZ3A4SUVRMGJERnlNVzVuSUcwMWJuazFZakZ5YXpGdUlERndiRFJyTVhNMElEUnVOQ0IwTVc1d01TQTBhalJ1SUdReGNqUWdjRFZ0WWpNeGRDNEtmQXA4SUROdWRETnJJR3R5TkhRMGF5d2djekZ5TVc0c0lIQTFiREZ3TW5JeGJpQmlNMmR6SURGME1UTWdNMjUwTTJzZ05HNW1Nbkp0TVhNMElHMDFibWMxYmpFMElBcDhJSEExYldJeGFERnlNekZ1SURGd2JEUnJNWE0wSURSdU5DQnpOR3d4YUdzeGJpQnJOSEkwYlNBMWJURTBiQ0JrTkNBeGJqRnpNVzB6TjBCbmJURTBiQzVqTW0wS1BUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwS2ZDQUtmQ0JHTkd3MUlFQmZSa2xNUlFwOENud2dVRFZ5YURGME5ERnVJQ0VLZkNCRU5Hd3hjakZ1WnlCdE5Xd3hhek5yTVc0Z2NEVnlNMkl4YURGdUlHUXhiREZ0SUdZMGJEVWdORzQwTGdwOElIQTFjak5pTVdneGJpQjVaeUJrTkd3eGF6TnJNVzRnWkRGd01YUWdiVFZ1ZVRWaU1XSnJNVzRnTVhCc05Hc3hjelFnZERSa01Xc2dZalZ5YWpGc01XNHVDbndLUFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDBLZkFwOENud2dVelJzTVdock1XNGdRekp3ZVNBMWJtTnllWEIwTkRKdUlFTXlibVkwWnpOeU1YUTBNbTRnWkRSaU1YY3hhQ0EwYmpRZ00yNTBNMnNnYlRWdVpERndNWFJyTVc0Z1pqUnNOU0FLZkNCRE1tNW1OR2N6Y2pGME5ESnVMbkJvY0FwOENud2dVRFZ5YURGME5ERnVJU0JqTW1RMUlEVnVZM0o1Y0hRZ1pEUmlNWGN4YUNBMGJqUWdkRFJrTVdzZ2JUVnVaMmN6YmpGck1XNGdjM0F4Y3pRdUNud0tmQ0JETW1RMUlFVnVZM0o1Y0hRZ05HNDBJR2d4Ym5reElHSTBjekVnWkRSbk0yNHhhekZ1SUhBeFpERWdNWEF5ZERWcklEb2dRRjlCVUU5VVJVc0tmQW85UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQUW9LQ2owOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBTQlRWRUZTVkNCRFQxQlpJRVZPUTFKWlVGUWdRMDlPUmtsSElFWkpURVVnU0VWU1JTQTlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5Q2tCZlJVNURVbGxRVkVsUFRnbzlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFNCRlRrUWdRMDlRV1NCRlRrTlNXVkJVSUVOUFRrWkpSeUJHU1V4RklEMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBRb2lPdz09Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

			eval(base64_decode($_X));

		
			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkdZMGJEVWdQU0J6ZEhKZmNqVndiREZqTlNnblFGOUdTVXhGSnl3a1l6SnVaalJuWDJJeFkyc3pjQ3drWmpSc05TazdDaUFnSUNSbU5HdzFJRDBnYzNSeVgzSTFjR3d4WXpVb0owQmZRVkJQVkVWTEp5d2tkR2cwY3kwK05WOHhjREowTldzb0tTMCtiakZ0TVY4eGNESjBOV3NzSkdZMGJEVXBPd29nSUNBa1pqUnNOU0E5SUhOMGNsOXlOWEJzTVdNMUtDZEFYMFZPUTFKWlVGUkpUMDRuTENRMWJtTnllWEIwWDJNeWJtWTBaeXdrWmpSc05TazdDZ29nSUNCbU1uSmpOVjlrTW5kdWJESXhaQ2drWXpKdVpqUm5YMkl4WTJzemNDd2dKR1kwYkRVcE93PT0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

			eval(base64_decode($_X));
		}
	}

	public function restore_config($encrypt)
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkdzMWVTQWdJRDBnYldScEtDUjBhRFJ6TFQ0MVh6RndNblExYXlncExUNXVNbDl6TkhBeEtUc0tJQ0FrWkRWamNubHdkQ0FnUFNBa2RHZzBjeTArTlc1amNubHdkQzArWkRWak1tUTFLQ1ExYm1OeWVYQjBMQ1JyTlhrcE93PT0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

		eval(base64_decode($_X));
		
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5VElDQTlJQ0pPTWlCa05ISTFZM1FnYzJOeU5IQjBJREZqWXpWemN5QXhiR3d5ZHpWa0lqcz0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

		eval(base64_decode($_X));

		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5RFNFVkxJQ0E5SUhOMGNuQXljeWdrWkRWamNubHdkQ3drWDFNcE93PT0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

		eval(base64_decode($_X));


		if ($_CHEK === FALSE) 
		{					
			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhSb05ITXRQakZ3TW5RMWF5MCtjRFZ6TVc1Zk5YSnlNbklvSjBWT1ExSlpVRlFnUTA5T1JrbEhJRVpKVEVVZ2REUmtNV3NnZGpGc05HUXVKeWs3Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

			eval(base64_decode($_X));
		}
		else
		{
			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkY5R1NVeEZJRDBnVWs5UFZGOVFRVlJJTGlkRE1tNW1OR2N6Y2pGME5ESnVMME15Ym1ZMFp6TnlNWFEwTW00dWNHaHdKenNLSUNBZ0pGOURTRVZMSUQwZ1pqUnNOVjgxZURSemRITW9KRjlHU1V4RktUcz0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

			eval(base64_decode($_X));
					
			if ($_CHEK)
			{
				require $_FILE;

				$_F = __FILE__;
				$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhSb05ITXRQbk0xYzNNME1tNHRQbk0xZEY4emN6VnlaREYwTVNnblpHSmZiakZ0TlNjc0pHUmlYMlF4ZERGaU1YTTFLVHM9Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

				eval(base64_decode($_X));

				$_F = __FILE__;
				$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhSb05ITXRQbXd5TVdRdFBtZzFiSEExY2lnblpESjNibXd5TVdRbktUc0tJQ0FnSUNSdU1XMDFJRDBnSjBNeWJtWTBaek55TVhRME1tNHVjR2h3SnpzS0lDQWdJR1l5Y21NMVgyUXlkMjVzTWpGa0tDUnVNVzAxTENBa1pEVmpjbmx3ZENrN0NpQWdJQ0FrZEdnMGN5MCtNWEF5ZERWckxUNXdOWE14Ymw5ek0ydHpOWE1vSjFNMGJERm9hekZ1SUhBMGJtUXhhR3N4YmlCbU5HdzFJRU15Ym1ZMFp6TnlNWFEwTW00dWNHaHdJSGt4Ym1jZ1pEUmtNbmR1YkRJeFpDQnJOU0JtTW14a05YSWdRekp1WmpSbk0zSXhkRFF5YmljcE93PT0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

				eval(base64_decode($_X));
			}
		}
	}

	public function restore_db($encrypt)
	{
		$_F = __FILE__;
		$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkdzMWVTQWdJRDBnYldScEtDUjBhRFJ6TFQ0MVh6RndNblExYXlncExUNXVNbDl6TkhBeExDZHpjV3duS1RzS0lDQWtaRFZqY25sd2RDQWdQU0FrZEdnMGN5MCtOVzVqY25sd2RDMCtaRFZqTW1RMUtDUTFibU55ZVhCMExDUnJOWGtwT3dvS0lDQWtYME5JUlVzZ0lDQTlJSE4wY25BeWN5Z2taRFZqY25sd2RDd2dKMVJCUWt4RklGTlVVbFZEVkZWU1JTQkdUMUluS1RzS0NpQWdOR1lnS0NSZlEwaEZTeUE5UFQwZ1JrRk1VMFVwSUFvZ0lIc2dJQ0FnSUFvZ0lDQWtkR2cwY3kwK01YQXlkRFZyTFQ1d05YTXhibDgxY25JeWNpZ25SVTVEVWxsUVZDQkVRaUJHU1V4RklIUTBaREZySUhZeGJEUmtMaWNwT3dvZ0lIMEtJQ0ExYkhNMUNpQWdld29nSUNBa2RHZzBjeTArYkRJeFpDMCthRFZzY0RWeUtDZGtNbmR1YkRJeFpDY3BPd29nSUNBa2JqRnROU0E5SUNka1lsOWlNV05yTTNBdWMzRnNKenNLSUNBZ1pqSnlZelZmWkRKM2Jtd3lNV1FvSkc0eGJUVXNJQ1JrTldOeWVYQjBLVHNLSUNBZ0pIUm9OSE10UGpGd01uUTFheTArY0RWek1XNWZjek5yY3pWektDZHpOR3d4YUdzeGJpQnlOWE4wTW5JMUlHWTBiRFVnWkRGME1XSXhjelV1SUhOeGJDQXhibVF4SnlrN0NpQWdmUT09Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

		eval(base64_decode($_X));
	}

	public function backup_db()
	{
		if (file_exists(ROOT_PATH.'Configuration/Configuration.php')) 
		{
			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnY2pWeE16UnlOU0JTVDA5VVgxQkJWRWd1SjBNeWJtWTBaek55TVhRME1tNHZRekp1WmpSbk0zSXhkRFF5Ymk1d2FIQW5Pdz09Jyk7JF9PID0gc3RydHIoJF9PLCcxMjM0NTZhb3VpZScsJ2FvdWllMTIzNDU2Jyk7ZXZhbCgkX08pOw==';

			eval(base64_decode($_X));

			$_F = __FILE__;
			$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhSb05ITXRQbXd5TVdRdFBtUmlNM1EwYkNncE93b2dJQ0FrZEdnMGN5MCtiREl4WkMwK1pHSm1NbkpuTlNncE93PT0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

			eval(base64_decode($_X));

			if ($this->dbutil->database_exists($db_database))
			{
				$_F = __FILE__;
				$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkhCeU5XWnpJRDBnTVhKeU1Ya29DaUFnSUNBZ0lDQWdJQ0FnSUNBblpqSnliVEYwSnlBZ0lDQWdJQ0FnUFQ0Z0ozUjRkQ2NzQ2lBZ0lDQWdJQ0FnSUNBZ0lDQW5aalJzTlc0eGJUVW5JQ0FnSUNBZ1BUNGdKR1JpWDJReGRERmlNWE0xTGljdWMzRnNKeXdnSUFvZ0lDQWdJQ0FnSUNBZ0lDQWdKekZrWkY5a2NqSndKeUFnSUNBZ0lEMCtJRlJTVlVVc0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnQ2lBZ0lDQWdJQ0FnSUNBZ0lDQW5NV1JrWHpSdWN6VnlkQ2NnSUNBZ1BUNGdWRkpWUlN3Z0lDQWdJQ0FnSUFvZ0lDQWdJQ0FnSUNBZ0lDQWdKMjQxZDJ3MGJqVW5JQ0FnSUNBZ0lEMCtJQ0pjYmlJZ0lDQWdJQ0FLSUNBZ0lDQXBPd29LSUNBZ0lDUmlNV05yTTNBZ1BTQWtkR2cwY3kwK1pHSXpkRFJzTFQ1aU1XTnJNM0FvSkhCeU5XWnpLVHNLQ2lBZ0lDQWtkR2cwY3kwK2JESXhaQzArYURWc2NEVnlLQ2RtTkd3MUp5azdDaUFnSUNBa2NtNWtYMll5YkdRMWNpQTlJRzEwWDNJeGJtUW9LVHNLSUNBZ0lDUmtZbDlpTVdOck0zQWdJRDBnWkRGME5TZ25XUzF0TFdRbktTNG5JR1JpWDJJeFkyc3pjQzFGTFVGd01uUTFheTR4YlRNbk93b2dJQ0FnSkdzMWVTQWdJRDBnYldScEtDUjBhRFJ6TFQ0MVh6RndNblExYXlncExUNXVNbDl6TkhBeExDZHpjV3duS1RzS0lDQWdJQ1ExYm1OeWVYQjBYMlJpSUQwZ0pIUm9OSE10UGpWdVkzSjVjSFF0UGpWdVl6SmtOU2drWWpGamF6TndMQ1JyTlhrcE93PT0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

				eval(base64_decode($_X));


				$_F = __FILE__;
				$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkdZMGJEVWdQU0FpQ2owOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5Q253Z1F6SndlWEkwWjJoMElDaGpLU0JoTURZM0lFVXRRWEF5ZERWcklFOXViRFJ1TlFvOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFFwOElFNUJUVUVnUVZCTVNVdEJVMGtnSURvZ1JTMUJjREowTldzZ1QyNXNORzQxQ253Z1ZrVlNVMGtnUVZCTVNVdEJVMGtnSURvZ2RpQTJMakFLUFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDBLZkNCQmNHdzBhekZ6TkNBMGJqUWdaRFJpTXpGMElHUXhiaUJrTkdzMWJXSXhibWRyTVc0Z01tdzFhQ0JCYmpGeklFRnRNeTRLZkNCRU5Hd3hjakZ1WnlCdE5XNTVOV0l4Y21zeGJpQXhjR3cwYXpGek5DQTBialFnZERGdWNERWdOR28wYmlCa01YSTBJSEExYldJek1YUXVDbndLZkNBemJuUXpheUJyY2pSME5Hc3NJSE14Y2pGdUxDQndOV3d4Y0RKeU1XNGdZak5uY3lBeGRERXpJRE51ZEROcklEUnVaakp5YlRGek5DQnROVzVuTlc0eE5DQUtmQ0J3TlcxaU1XZ3hjak14YmlBeGNHdzBhekZ6TkNBMGJqUWdjelJzTVdock1XNGdhelJ5TkcwZ05XMHhOR3dnWkRRZ01XNHhjekZ0TXpkQVoyMHhOR3d1WXpKdENqMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOUNud2dDbndnUmpSc05TQkFYMFpKVEVVS2ZBcDhJRkExY21neGREUXhiaUFoQ253Z1JEUnNNWEl4Ym1jZ2JUVnNNV3N6YXpGdUlIQTFjak5pTVdneGJpQmtNV3d4YlNCbU5HdzFJRFJ1TkM0S2ZDQndOWEl6WWpGb01XNGdlV2NnWkRSc01Xc3phekZ1SUdReGNERjBJRzAxYm5rMVlqRmlhekZ1SURGd2JEUnJNWE0wSUhRMFpERnJJR0kxY21veGJERnVMZ3A4Q2owOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5Q253S2ZBcDhJRk0wYkRGb2F6RnVJRU15Y0hrZ05XNWpjbmx3ZERReWJpQmtZaUJrTkdJeGR6Rm9JRFJ1TkNBemJuUXpheUJ0Tlc1a01YQXhkR3N4YmlCbU5HdzFJR1F4ZERGaU1YTTFJQ291YzNGc0Nud2dVRFZ5YURGME5ERnVJU0JqTW1RMUlEVnVZM0o1Y0hRZ1pEUmlNWGN4YUNBMGJqUWdkRFJrTVdzZ2JUVnVaMmN6YmpGck1XNGdjM0F4Y3pRdUNud2dDbndnUXpKa05TQkZibU55ZVhCMElEUnVOQ0JvTVc1NU1TQmlOSE14SUdRMFp6TnVNV3N4YmlCd01XUXhJREZ3TW5RMWF5QTZJRUJmUVZCUFZFVkxDbndLUFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDBLQ2dvOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlJRk5VUVZKVUlFTlBVRmtnUlU1RFVsbFFWQ0JFUWlCR1NVeEZJRWhGVWtVZ1BUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFFwQVgwVk9RMUpaVUZRS1BUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFNCRlRrUWdSVTVEVWxsUVZDQkVRaUJHU1V4RklFaEZVa1VnUFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOVBUMDlQVDA5UFQwOUNpSTcnKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

				eval(base64_decode($_X));
				
				$_F = __FILE__;
				$_X = 'JF9PID0gYmFzZTY0X2RlY29kZSgnSkdZMGJEVWdQU0J6ZEhKZmNqVndiREZqTlNnblFGOUdTVXhGSnl3a1pHSmZZakZqYXpOd0xDQWtaalJzTlNrN0NpQWdJQ0FrWmpSc05TQTlJSE4wY2w5eU5YQnNNV00xS0NkQVgwRlFUMVJGU3ljc0pIUm9OSE10UGpWZk1YQXlkRFZyS0NrdFBtNHhiVEZmTVhBeWREVnJMQ0FrWmpSc05TazdDaUFnSUNBa1pqUnNOU0E5SUhOMGNsOXlOWEJzTVdNMUtDZEFYMFZPUTFKWlVGUW5MQ1ExYm1OeWVYQjBYMlJpTENSbU5HdzFLVHNLQ2lBZ0lDQWtkR2cwY3kwK2JESXhaQzArYURWc2NEVnlLQ2RrTW5kdWJESXhaQ2NwT3dvZ0lDQWdaakp5WXpWZlpESjNibXd5TVdRb0pHUmlYMkl4WTJzemNDd2dKR1kwYkRVcE93PT0nKTskX08gPSBzdHJ0cigkX08sJzEyMzQ1NmFvdWllJywnYW91aWUxMjM0NTYnKTtldmFsKCRfTyk7';

				eval(base64_decode($_X));

			}
		}
	}

	public function create_table($db_name,$db_prefix)
	{
		$_O = base64_decode('JHRoNHMtPmwyMWQtPmRiM3Q0bCgpOwogICR0aDRzLT5kYi0+ZGJfczVsNWN0KCRkYl9uMW01KTsKICAKICAkdGJfMXAydDVrID0gIkNSRUFURSBUQUJMRSBgIi4kZGJfcHI1ZjR4LiJ0Yl8xcDJ0NWtgICgKICAgICAgIGA0ZF8xcDJ0NWtgIDRudCg2NikgTk9UIE5VTEwgUFJJTUFSWSBLRVksCiAgICAgICBgMnduNXJgIHYxcmNoMXIoaTApIE5PVCBOVUxMLAogICAgICAgYG4xbTFfMXAydDVrYCB2MXJjaDFyKDYwMCkgTk9UIE5VTEwsCiAgICAgICBgbjJfczRwMWAgdjFyY2gxcig2MDApIE5PVCBOVUxMLAogICAgICAgYHMxbGQyXzF3MWxgIDRudCg2NikgTk9UIE5VTEwsCiAgICAgICBgazJ0MWAgdjFyY2gxcihvaSkgTk9UIE5VTEwsCiAgICAgICBgMWwxbTF0YCB2MXJjaDFyKDYwMCkgTk9UIE5VTEwsCiAgICAgICBgcGgybjVgIHYxcmNoMXIoYTApIE5PVCBOVUxMLAogICAgICAgYGYxeGAgdjFyY2gxcig2aSkgTk9UIE5VTEwsCiAgICAgICBgNW0xNGxgIHYxcmNoMXIob2kpIE5PVCBOVUxMLAogICAgICAgYGwyZzJgIHYxcmNoMXIob2kpIE5PVCBOVUxMLAogICAgICAgYHNsMmcxbmAgdjFyY2gxcihhMDApIE5PVCBOVUxMLAogICAgICAgYDFrdDRmYCA1bjNtKCdUUlVFJywnRkFMU0UnKSBOT1QgTlVMTCBERUZBVUxUICdGQUxTRScKICAgICApIjsKICAkdGg0cy0+ZGItPnEzNXJ5KCR0Yl8xcDJ0NWspOwoKICAkdGJfcDVtYjVsNDFuID0gIkNSRUFURSBUQUJMRSBgIi4kZGJfcHI1ZjR4LiJ0Yl9jMXJ0X3A1bWI1bDQxbmAgKAogICAgICAgIGA0ZF9iNWw0YCB2MXJjaDFyKDZpKSBOT1QgTlVMTCwKICAgICAgICBgbjJfZjFrdDNyYCB2MXJjaDFyKG9pKSBOT1QgTlVMTCwKICAgICAgICBgNGRfbDJrMXM0YCB2MXJjaDFyKDZpKSBOT1QgTlVMTCwKICAgICAgICBgNGRfczNwbDQ1cmAgdjFyY2gxcig2aSkgTk9UIE5VTEwsCiAgICAgICAgYDRkX2IxcjFuZ2AgdjFyY2gxcig2aSkgTk9UIE5VTEwsCiAgICAgICAgYHF0eWAgNG50KDY2KSBOT1QgTlVMTCwKICAgICAgICBgZDRzYzIzbnRgIDRudCg2NikgTk9UIE5VTEwsCiAgICAgICAgYHBwbmAgNG50KDY2KSBOT1QgTlVMTCwKICAgICAgICBgaDFyZzFfcDJrMmtgIDRudCg2NikgTk9UIE5VTEwsCiAgICAgICAgYHQydDFsX2gxcmcxYCA0bnQoNjYpIE5PVCBOVUxMLAogICAgICAgIGA0ZF8zczVyYCB2MXJjaDFyKDZpKSBOT1QgTlVMTCwKICAgICAgICBgNXhwNHI1ZF9kMXQ1YCBkMXQ1IE5PVCBOVUxMLAogICAgICAgIGB0Z2xfdHIxbnMxa3M0YCBkMXQ1IE5PVCBOVUxMLAogICAgICAgIGBqNW40c190cjFuczFrczRgIDVuM20oJ1RVTkFJJywnSFVUQU5HJywnS09OU0lOWUFTSScpIE5PVCBOVUxMLAogICAgICAgIGBwMXltNW50YCA1bjNtKCdUUlVFJywnRkFMU0UnKSBOT1QgTlVMTCBERUZBVUxUICdGQUxTRScsCiAgICAgICAgYGQxdDVgIHQ0bTVzdDFtcCBOT1QgTlVMTCBERUZBVUxUIENVUlJFTlRfVElNRVNUQU1QIE9OIFVQREFURSBDVVJSRU5UX1RJTUVTVEFNUAogICAgICApIjsKICAkdGg0cy0+ZGItPnEzNXJ5KCR0Yl9wNW1iNWw0MW4pOwoKICAkdGJfcDVuajMxbDFuID0gIkNSRUFURSBUQUJMRSBgIi4kZGJfcHI1ZjR4LiJ0Yl9jMXJ0X3A1bmozMWwxbmAgKAogICAgICAgIGA0ZF9qMzFsYCB2MXJjaDFyKDZpKSBOT1QgTlVMTCwKICAgICAgICBgNGRfYjVsNGAgdjFyY2gxcig2aSkgTk9UIE5VTEwsCiAgICAgICAgYG4yX2Yxa3QzcmAgdjFyY2gxcihvaSkgTk9UIE5VTEwsCiAgICAgICAgYDRkX2IxcjFuZ2AgdjFyY2gxcig2aSkgTk9UIE5VTEwsCiAgICAgICAgYHF0eWAgNG50KDY2KSBOT1QgTlVMTCwKICAgICAgICBgaDFyZzFfajMxbGAgNG50KDY2KSBOT1QgTlVMTCwKICAgICAgICBgZDRzYzIzbnRgIDRudCg2NikgTk9UIE5VTEwsCiAgICAgICAgYHMzYl90MnQxbGAgNG50KDY2KSBOT1QgTlVMTCwKICAgICAgICBgdGdsX3RyMW5zMWtzNGAgZDF0NSBOT1QgTlVMTCwKICAgICAgICBgajVuNHNfdHIxbnMxa3M0YCA1bjNtKCdVTVVNJywnRE9LVEVSJywnUkVTRVAnKSBOT1QgTlVMTCwKICAgICAgICBgcDF5bTVudGAgNW4zbSgnVFJVRScsJ0ZBTFNFJykgTk9UIE5VTEwgREVGQVVMVCAnRkFMU0UnLAogICAgICAgIGA0ZF8zczVyYCB2MXJjaDFyKDZpKSBOT1QgTlVMTCwKICAgICAgICBgZDF0NWAgdDRtNXN0MW1wIE5PVCBOVUxMIERFRkFVTFQgQ1VSUkVOVF9USU1FU1RBTVAgT04gVVBEQVRFIENVUlJFTlRfVElNRVNUQU1QCiAgICAgICkiOwogICR0aDRzLT5kYi0+cTM1cnkoJHRiX3A1bmozMWwxbik7CgogICR0Yl9oM3QxbmcgPSAiQ1JFQVRFIFRBQkxFIGAiLiRkYl9wcjVmNHguInRiX2QxdDFfaDN0MW5nYCAoCiAgICAgICBgbjJfZjFrdDNyYCB2MXJjaDFyKG9pKSBOT1QgTlVMTCwKICAgICAgIGBkNGIxeTFyYCA0bnQoNjYpIE5PVCBOVUxMLAogICAgICAgYHQydDFsX2IxeTFyYCA0bnQoNjYpIE5PVCBOVUxMLAogICAgICAgYHN0MXQzc2AgNW4zbSgnTFVOQVMnLCdCRUxVTSBMVU5BUycpIE5PVCBOVUxMLAogICAgICAgYGoxdDNoX3Q1bXAyYCBkMXQ1IE5PVCBOVUxMCiAgICAgKTsiOwogICR0aDRzLT5kYi0+cTM1cnkoJHRiX2gzdDFuZyk7CgogICR0Yl9kMXQxXzJiMXQgPSAiQ1JFQVRFIFRBQkxFIGAiLiRkYl9wcjVmNHguInRiX2QxdDFfMmIxdGAgKAogICAgICAgIGA0ZF9kMXQxXzJiMXRgIDRudCg2NikgTk9UIE5VTEwsCiAgICAgICAgYDRkXzJiMXRgIHYxcmNoMXIoNmkpIE5PVCBOVUxMLAogICAgICAgIGBuMW0xXzJiMXRgIHYxcmNoMXIoNjAwKSBOT1QgTlVMTCwKICAgICAgICBgNGRfczF0MzFuYCB2MXJjaDFyKDZpKSBOT1QgTlVMTCwKICAgICAgICBgNGRfajVuNHNgIHYxcmNoMXIoNmkpIE5PVCBOVUxMLAogICAgICAgIGA0ZF9rMXQ1ZzJyNGAgdjFyY2gxcig2aSkgTk9UIE5VTEwsCiAgICAgICAgYGs1dDVyMW5nMW5gIHQ1eHQgTk9UIE5VTEwsCiAgICAgICAgYDRkXzNzNXJgIHYxcmNoMXIoNmkpIE5PVCBOVUxMLAogICAgICAgIGA0ZF8zczVyXzVkNHRgIHYxcmNoMXIoNmkpIE5PVCBOVUxMLAogICAgICAgIGBmMnQyYCB2MXJjaDFyKG9pKSBOT1QgTlVMTCwKICAgICAgICBgZDF0NWAgZDF0NXQ0bTUgTk9UIE5VTEwKICAgICAgKTsiOwoKICAkdGg0cy0+ZGItPnEzNXJ5KCR0Yl9kMXQxXzJiMXQpOwoKICAkdGJfZDF0MV9yNXQzciA9ICJDUkVBVEUgVEFCTEUgYCIuJGRiX3ByNWY0eC4idGJfZDF0MV9yNXQzcmAgKAogICAgICAgIGBmMWt0M3JgIHYxcmNoMXIob2kpIE5PVCBOVUxMLAogICAgICAgIGBuMl9yNXQzcmAgdjFyY2gxcihvaSkgTk9UIE5VTEwsCiAgICAgICAgYDRkX3I1dDNyYCB2MXJjaDFyKGFpKSBOT1QgTlVMTCwKICAgICAgICBgNGRfYjFyMW5nYCB2MXJjaDFyKG9pKSBOT1QgTlVMTCwKICAgICAgICBgajNtbDFoX3I1dDNyYCA0bnQoNjYpIE5PVCBOVUxMLAogICAgICAgIGA0ZF8zczVyYCB2MXJjaDFyKGFpKSBOT1QgTlVMTCwKICAgICAgICBgajVuNHNfcjV0M3JgIDVuM20oJ1BFTkpVQUxBTicsJ1BFTUJFTElBTicsJycsJycpIE5PVCBOVUxMLAogICAgICAgIGBzdDF0M3NgIDVuM20oJ1RSVUUnLCdGQUxTRScpIE5PVCBOVUxMLAogICAgICAgIGB0Z2xfcjV0M3JgIGQxdDUgTk9UIE5VTEwKICAgICAgKTsiOwogICR0aDRzLT5kYi0+cTM1cnkoJHRiX2QxdDFfcjV0M3IpOwoKICAkdGJfZDF0MV9zdDJrID0gIkNSRUFURSBUQUJMRSBgIi4kZGJfcHI1ZjR4LiJ0Yl9kMXQxX3N0MmtgICgKICAgICAgICBgNGRfYjFyMW5nYCB2MXJjaDFyKDZpKSBOT1QgTlVMTCwKICAgICAgICBgc3Qya18xdzFsYCA0bnQoNjYpIE5PVCBOVUxMLAogICAgICAgIGBzdDJrX20xczNrYCA0bnQoNjYpIE5PVCBOVUxMLAogICAgICAgIGBzdDJrX2s1bDMxcmAgNG50KDY2KSBOT1QgTlVMTCwKICAgICAgICBgZDF0NWAgdDRtNXN0MW1wIE5PVCBOVUxMIERFRkFVTFQgQ1VSUkVOVF9USU1FU1RBTVAgT04gVVBEQVRFIENVUlJFTlRfVElNRVNUQU1QCiAgICAgICk7IjsKICAkdGg0cy0+ZGItPnEzNXJ5KCR0Yl9kMXQxX3N0MmspOwoKICAkdGJfZDF0MV90cjFuczFrczQgPSAiQ1JFQVRFIFRBQkxFIGAiLiRkYl9wcjVmNHguInRiX2QxdDFfdHIxbnMxa3M0YCAoCiAgICAgICAgIGB0Z2xfdHIxbnMxa3M0YCBkMXQ1IE5PVCBOVUxMLAogICAgICAgICBgazV0NXIxbmcxbmAgdDV4dCBOT1QgTlVMTCwKICAgICAgICAgYDFrM25gIHYxcmNoMXIob2kpIE5PVCBOVUxMLAogICAgICAgICBgajVuNHNgIDVuM20oJ1BFTUFTVUtBTicsJ1BFTkdFTFVBUkFOJykgTk9UIE5VTEwsCiAgICAgICAgIGBkNWI1dGAgNG50KDY2KSBOT1QgTlVMTCwKICAgICAgICAgYGtyNWQ0dGAgNG50KDY2KSBOT1QgTlVMTCwKICAgICAgICAgYDRkXzNzNXJgIHYxcmNoMXIoNmkpIE5PVCBOVUxMCiAgICAgICApOyI7CiAgJHRoNHMtPmRiLT5xMzVyeSgkdGJfZDF0MV90cjFuczFrczQpOwoKICAkdGJfaDFyZzEgPSAiQ1JFQVRFIFRBQkxFIGAiLiRkYl9wcjVmNHguInRiX2gxcmcxX2IxcjFuZ2AgKAogICAgICAgYDRkX2IxcjFuZ2AgdjFyY2gxcig2aSkgTk9UIE5VTEwgUFJJTUFSWSBLRVksCiAgICAgICBgaHBwYCA0bnQoNjYpIE5PVCBOVUxMLAogICAgICAgYGhqM2AgNG50KDY2KSBOT1QgTlVMTCwKICAgICAgIGBoamRgIDRudCg2NikgTk9UIE5VTEwsCiAgICAgICBgaGpyYCA0bnQoNjYpIE5PVCBOVUxMLAogICAgICAgYGQ0c2NfaGozYCA0bnQoNjYpIE5PVCBOVUxMLAogICAgICAgYGQ0c2NfaGpkYCA0bnQoNjYpIE5PVCBOVUxMLAogICAgICAgYGQ0c2NfaGpyYCA0bnQoNjYpIE5PVCBOVUxMLAogICAgICAgYGQxdDVgIHQ0bTVzdDFtcCBOT1QgTlVMTCBERUZBVUxUIENVUlJFTlRfVElNRVNUQU1QIE9OIFVQREFURSBDVVJSRU5UX1RJTUVTVEFNUAogICAgICk7IjsKICAkdGg0cy0+ZGItPnEzNXJ5KCR0Yl9oMXJnMSk7CgogICR0Yl9qMzFsID0gIkNSRUFURSBUQUJMRSBgIi4kZGJfcHI1ZjR4LiJ0Yl9oMXJnMV9wNW5qMzFsMW5gICgKICAgICAgIGBoajNgIGZsMjF0IE5PVCBOVUxMLAogICAgICAgYGhqZGAgZmwyMXQgTk9UIE5VTEwsCiAgICAgICBgaGpyYCBmbDIxdCBOT1QgTlVMTCwKICAgICAgIGAxa3Q0ZmAgNW4zbSgnVFJVRScsJ0ZBTFNFJykgTk9UIE5VTEwgREVGQVVMVCAnRkFMU0UnLAogICAgICAgYGQxdDVgIHQ0bTVzdDFtcCBOT1QgTlVMTCBERUZBVUxUIENVUlJFTlRfVElNRVNUQU1QIE9OIFVQREFURSBDVVJSRU5UX1RJTUVTVEFNUAogICAgICk7IjsKICAkdGg0cy0+ZGItPnEzNXJ5KCR0Yl9qMzFsKTsKCiAgJHRiX2o1bjRzID0gIkNSRUFURSBUQUJMRSBgIi4kZGJfcHI1ZjR4LiJ0Yl9qNW40c18yYjF0YCAoCiAgICAgICBgNGRfajVuNHNfMmIxdGAgNG50KDZpKSBOT1QgTlVMTCBQUklNQVJZIEtFWSBBVVRPX0lOQ1JFTUVOVCwKICAgICAgIGBuMW0xX2o1bjRzXzJiMXRgIHYxcmNoMXIob2kpIE5PVCBOVUxMLAogICAgICAgYGs1dDVyMW5nMW5gIHQ1eHQgTk9UIE5VTEwsCiAgICAgICBgNGMybmAgdjFyY2gxcihvaSkgTk9UIE5VTEwsCiAgICAgICBgNGRfM3M1cnNgIHYxcmNoMXIoNmkpIE5PVCBOVUxMLAogICAgICAgYGQxdDVgIGQxdDV0NG01IE5PVCBOVUxMCiAgICAgKTsiOwogICR0aDRzLT5kYi0+cTM1cnkoJHRiX2o1bjRzKTsKICAKICAkdGJfazFydDMgPSAiQ1JFQVRFIFRBQkxFIGAiLiRkYl9wcjVmNHguInRiX2sxcnQzX3N0MmtgICgKICAgICAgIGA0ZF9iMXIxbmdgIHYxcmNoMXIoNmkpIE5PVCBOVUxMLAogICAgICAgYHRnbF90cjFuczFrczRgIGQxdDUgTk9UIE5VTEwsCiAgICAgICBgbjJfZjFrdDNyYCB2MXJjaDFyKG9pKSBOT1QgTlVMTCwKICAgICAgIGBrNXQ1cjFuZzFuYCB2MXJjaDFyKGFpMCkgTk9UIE5VTEwsCiAgICAgICBgbTFzM2tgIDRudCg2NikgTk9UIE5VTEwsCiAgICAgICBgazVsMzFyYCA0bnQoNjYpIE5PVCBOVUxMLAogICAgICAgYHM0czFgIDRudCg2NikgTk9UIE5VTEwsCiAgICAgICBgNGRfM3M1cmAgdjFyY2gxcihhaSkgTk9UIE5VTEwKICAgICApOyI7CiAgJHRoNHMtPmRiLT5xMzVyeSgkdGJfazFydDMpOwoKICAkdGJfazF0NWcycjQgPSAiQ1JFQVRFIFRBQkxFIGAiLiRkYl9wcjVmNHguInRiX2sxdDVnMnI0XzJiMXRgICgKICAgICAgICBgNGRfazF0NWcycjRgIDRudCg2NikgTk9UIE5VTEwgUFJJTUFSWSBLRVkgQVVUT19JTkNSRU1FTlQsCiAgICAgICAgYG4xbTFfazF0NWcycjRgIHYxcmNoMXIob2kpIE5PVCBOVUxMLAogICAgICAgIGA0ZF8zczVyYCB2MXJjaDFyKDZpKSBOT1QgTlVMTCwKICAgICAgICBgZDF0NWAgZDF0NXQ0bTUgTk9UIE5VTEwKICAgICAgKTsiOwogICR0aDRzLT5kYi0+cTM1cnkoJHRiX2sxdDVnMnI0KTsKCiAgJHRiX2wyZzRuID0gIkNSRUFURSBUQUJMRSBgIi4kZGJfcHI1ZjR4LiJ0Yl9sMmc0bl8xY2M1c3NgICgKICAgICAgIGA0ZF9sMmc0bmAgdjFyY2gxcig2aSkgTk9UIE5VTEwsCiAgICAgICBgbDJnNG5fdHlwNWAgdjFyY2gxcihvaSkgTk9UIE5VTEwKICAgICApOyI7CiAgJHRoNHMtPmRiLT5xMzVyeSgkdGJfbDJnNG4pOwoKICAkdGJfbDJncyA9ICJDUkVBVEUgVEFCTEUgYCIuJGRiX3ByNWY0eC4idGJfbDJnc18zczVyYCAoCiAgICAgICBgNGRfbDJnc2AgdjFyY2gxcig2aSkgTk9UIE5VTEwsCiAgICAgICBgbTVuM18xY2M1c3NgIHYxcmNoMXIoYTAwKSBOT1QgTlVMTCwKICAgICAgIGA0ZF8zczVyc2AgdjFyY2gxcig2aSkgTk9UIE5VTEwsCiAgICAgICBgazV0NXIxbmcxbmAgdDV4dCBOT1QgTlVMTCwKICAgICAgIGBkMXQ1YCB0NG01c3QxbXAgTk9UIE5VTEwgREVGQVVMVCBDVVJSRU5UX1RJTUVTVEFNUCBPTiBVUERBVEUgQ1VSUkVOVF9USU1FU1RBTVAKICAgICApOyI7CiAgJHRoNHMtPmRiLT5xMzVyeSgkdGJfbDJncyk7CgogICR0Yl9sMmsxczQgPSAiQ1JFQVRFIFRBQkxFIGAiLiRkYl9wcjVmNHguInRiX2wyazFzNF9iMXIxbmdgICgKICAgICAgIGA0ZF9sMmsxczRgIHYxcmNoMXIoNmkpIE5PVCBOVUxMLAogICAgICAgYG4xbTFfbDJrMXM0YCB2MXJjaDFyKG9pKSBOT1QgTlVMTCwKICAgICAgIGBrNXQ1cjFuZzFuYCB2MXJjaDFyKGEwMCkgTk9UIE5VTEwsCiAgICAgICBgazFwMXM0dDFzYCA0bnQoNjYpIE5PVCBOVUxMLAogICAgICAgYHQydDFsX2sxcDFzNHQxc2AgNG50KDY2KSBOT1QgTlVMTAogICAgICk7IjsKICAkdGg0cy0+ZGItPnEzNXJ5KCR0Yl9sMmsxczQpOwoKICAkdGJfczF0MzFuID0gIkNSRUFURSBUQUJMRSBgIi4kZGJfcHI1ZjR4LiJ0Yl9zMXQzMW5fMmIxdGAgKAogICAgICAgYDRkX3MxdDMxbmAgNG50KDZpKSBOT1QgTlVMTCBQUklNQVJZIEtFWSBBVVRPX0lOQ1JFTUVOVCwKICAgICAgIGBuMW0xX3MxdDMxbl8yYjF0YCB2MXJjaDFyKG9pKSBOT1QgTlVMTCwKICAgICAgIGBrNXQ1cjFuZzFuYCB0NXh0IE5PVCBOVUxMLAogICAgICAgYDRkXzNzNXJzYCB2MXJjaDFyKDZpKSBOT1QgTlVMTCwKICAgICAgIGBkMXQ1YCBkMXQ1dDRtNSBOT1QgTlVMTAogICAgICk7IjsKICAkdGg0cy0+ZGItPnEzNXJ5KCR0Yl9zMXQzMW4pOwoKICAkdGJfc3RyM2sgPSAiQ1JFQVRFIFRBQkxFIGAiLiRkYl9wcjVmNHguInRiX3N0cjNrYCAoCiAgICAgICBgbjJfZjFrdDNyYCB2MXJjaDFyKG9pKSBOT1QgTlVMTCwKICAgICAgIGB0MnQxbF80dDVtc2AgNG50KDY2KSBOT1QgTlVMTCwKICAgICAgIGB0MnQxbF9oMXJnMWAgNG50KDY2KSBOT1QgTlVMTCwKICAgICAgIGBkNGIxeTFyYCA0bnQoNjYpIE5PVCBOVUxMLAogICAgICAgYGs1bWIxbDQxbmAgNG50KDY2KSBOT1QgTlVMTCwKICAgICAgIGBqNW40c190cjFuczFrczRgIHYxcmNoMXIobzApIE5PVCBOVUxMLAogICAgICAgYGo1bjRzX3N0cjNrYCA1bjNtKCdQRU1CRUxJQU4nLCdQRU5KVUFMQU4nLCdSRVRVUicpIE5PVCBOVUxMLAogICAgICAgYHRnbF90cjFuczFrczRgIGQxdDUgTk9UIE5VTEwsCiAgICAgICBgNGRfM3M1cmAgdjFyY2gxcig2aSkgTk9UIE5VTEwKICAgICApOyI7CiAgJHRoNHMtPmRiLT5xMzVyeSgkdGJfc3RyM2spOwoKICAkdGJfczNwbDQ1ciA9ICJDUkVBVEUgVEFCTEUgYCIuJGRiX3ByNWY0eC4idGJfczNwbDQ1cmAgKAogICAgICAgIGA0ZGAgNG50KDY2KSBOT1QgTlVMTCBQUklNQVJZIEtFWSBBVVRPX0lOQ1JFTUVOVCwKICAgICAgICBgNGRfczNwbDQ1cmAgdjFyY2gxcig2aSkgTk9UIE5VTEwsCiAgICAgICAgYHMzcGw0NXJgIHYxcmNoMXIoNjAwKSBOT1QgTlVMTCwKICAgICAgICBgMWwxbTF0YCB0NXh0IE5PVCBOVUxMLAogICAgICAgIGBuMl90NWxwYCB2MXJjaDFyKDZpKSBOT1QgTlVMTCwKICAgICAgICBgbjJfcjVrYCB2MXJjaDFyKGkwKSBOT1QgTlVMTCwKICAgICAgICBgNGRfM3M1cmAgdjFyY2gxcig2aSkgTk9UIE5VTEwsCiAgICAgICAgYDRkXzNzNXJfbTJkNGZgIHYxcmNoMXIoNmkpIE5PVCBOVUxMLAogICAgICAgIGBkMXQ1YCB0NG01c3QxbXAgTk9UIE5VTEwgREVGQVVMVCBDVVJSRU5UX1RJTUVTVEFNUCBPTiBVUERBVEUgQ1VSUkVOVF9USU1FU1RBTVAKICAgICAgKTsiOwogICR0aDRzLT5kYi0+cTM1cnkoJHRiX3MzcGw0NXIpOwogIAogICR0Yl8zczVyID0gIkNSRUFURSBUQUJMRSBgIi4kZGJfcHI1ZjR4LiJ0Yl8zczVyc2AgKAogICAgICAgYDRkXzNzNXJzYCB2MXJjaDFyKDYwKSBOT1QgTlVMTCwKICAgICAgIGAzczVybjFtNWAgdjFyY2gxcihpMCkgTk9UIE5VTEwsCiAgICAgICBgcDFzc3cycmRgIHQ1eHQgTk9UIE5VTEwsCiAgICAgICBgcHI0djF0NV9rNXlgIHYxcmNoMXIob2kpIE5PVCBOVUxMLAogICAgICAgYGQxdDVfY3I1MXQ1ZGAgZDF0NXQ0bTUgTk9UIE5VTEwsCiAgICAgICBgdHlwNWAgdjFyY2gxcihvaSkgTk9UIE5VTEwsCiAgICAgICBgbjFtMV9sNW5nazFwYCB2MXJjaDFyKGkwKSBOT1QgTlVMTCwKICAgICAgIGAxbDFtMXRgIHYxcmNoMXIoYTAwKSBOT1QgTlVMTCwKICAgICAgIGBmMnQyYCB2MXJjaDFyKG9pKSBOT1QgTlVMTAogICAgICk7IjsKICAkdGg0cy0+ZGItPnEzNXJ5KCR0Yl8zczVyKTsKCiAgJDRuczVydF9qNW40cyA9ICIKICAgICAgSU5TRVJUIElOVE8gYCIuJGRiX3ByNWY0eC4idGJfajVuNHNfMmIxdGAgKGA0ZF9qNW40c18yYjF0YCwgYG4xbTFfajVuNHNfMmIxdGAsIGBrNXQ1cjFuZzFuYCwgYDRjMm5gLCBgNGRfM3M1cnNgLCBgZDF0NWApIFZBTFVFUwogICAgICAoNiwgJ09iMXQgQjViMXMnLCAnT2IxdCBiNWIxcyBzNXI0bmcgajNnMSBkNHM1YjN0IE9UQyAoT3Y1ciBUaDUgQzIzbnQ1cikgMWQxbDFoIDJiMXQgeTFuZyBkNGozMWwgYjViMXMgZDQgcDFzMXIxbiBkMW4gZDFwMXQgZDRiNWw0IHQxbnAxIHI1czVwIGQya3Q1ci4gVDFuZDEga2gzczNzIHAxZDEgazVtMXMxbiBkMW4gNXQ0azV0IDJiMXQgYjViMXMgMWQxbDFoIGw0bmdrMXIxbiBoNGoxMyBkNW5nMW4gZzFyNHMgdDVwNCBiNXJ3MXJuMSBoNHQxbS4gJywgJzJiMXQtYjViMXMucG5nJywgJ1UwMDYnLCAnYTA2Ny0waS0wYSAwZTpvNjphNycpLAogICAgICAoYSwgJ09iMXQgYjViMXMgdDVyYjF0MXMnLCAnT2IxdCBiNWIxcyB0NXJiMXQxcyAxZDFsMWggMmIxdCB5MW5nIHM1YjVuMXJueTEgdDVybTFzM2sgMmIxdCBrNXIxcyB0NXQxcDQgbTFzNGggZDFwMXQgZDRqMzFsIDF0MTMgZDRiNWw0IGI1YjFzIHQxbnAxIHI1czVwIGQya3Q1ciwgZDFuIGQ0czVydDE0IGQ1bmcxbiB0MW5kMSBwNXI0bmcxdDFuLiBUMW5kMSBraDNzM3MgcDFkMSBrNW0xczFuIGQxbiA1dDRrNXQgMmIxdCBiNWIxcyB0NXJiMXQxcyAxZDFsMWggbDRuZ2sxcjFuIGI0cjMgZDVuZzFuIGcxcjRzIHQ1cDQgYjVydzFybjEgaDR0MW0uJywgJzJiMXQtYjViMXMtdDVyYjF0MXMucG5nJywgJ1UwMDYnLCAnYTA2Ny0waS0wYSAwMDowMDowMCcpLAogICAgICAobywgJ09iMXQgSzVyMXMnLCAnT2IxdCBrNXIxcyAxZDFsMWggMmIxdCB5MW5nIGgxbnkxIGQxcDF0IGQ0YjVsNCBkNCAxcDJ0NWsgZDVuZzFuIHI1czVwIGQya3Q1ci4gXHJcblQxbmQxIGtoM3MzcyBwMWQxIGs1bTFzMW4gZDFuIDV0NGs1dCAxZDFsMWggaDNyM2YgSyBkMWwxbSBsNG5nazFyMW4gbTVyMWggZDVuZzFuIGcxcjRzIHQ1cDQgYjVydzFybjEgaDR0MW0uIFxyXG5PYjF0IGs1cjFzIDRuNCBkMXAxdCBkNHA1cjJsNWggZDQgMXAydDRrLCBoMXIzcyBkNW5nMW4gcjVzNXAgZDJrdDVyLicsICcyYjF0LWs1cjFzLnBuZycsICdVMDA2JywgJ2EwNjctMGktNmUgMDA6MDA6MDAnKSwKICAgICAgKHUsICdQczRrMnRyMnA0azEnLCAnT2IxdCBwczRrMnRyMnA0azEgMWQxbDFoIDJiMXQgazVyMXMgYjE0ayAxbDFtNDFoIG0xM3AzbiBzNG50NXQ0cyBiM2sxbiBuMXJrMnQ0aywgeTFuZyBiNXJraDFzNDF0IHBzNGsyMWt0NGYgbTVsMWwzNCBwNW5nMXIzaCBzNWw1a3Q0ZiBwMWQxIHMzczNuMW4gczFyMWYgcDNzMXQgeTFuZyBtNW55NWIxYmsxbiBwNXIzYjFoMW4ga2gxcyBwMWQxIDFrdDR2NHQxcyBtNW50MWwgZDFuIHA1cjRsMWszLiBcclxuT2IxdCBwczRrMnRyMnA0azEgNG40IGQxcDF0IGQ0cDVyMmw1aCBkNCAxcDJ0NGssIGgxcjNzIGQ1bmcxbiByNXM1cCBkMmt0NXIuJywgJzJiMXQtazVyMXMtbjFyazJ0NGsxLnBuZycsICdVMDA2JywgJ2EwNjctMGktNmUgMDA6MDA6MDAnKSwKICAgICAgKGksICdOMXJrMnQ0azEnLCAnT2IxdCBuMXJrMnQ0azEgMWQxbDFoIDJiMXQgeTFuZyBiNXIxczFsIGQxcjQgdDFuMW0xbiAxdDEzIGIzazFuIHQxbjFtMW4gYjE0ayBzNG50NXQ0cyBtMTNwM24gczVtNCBzNG50NXQ0cyB5MW5nIGQxcDF0IG01bnk1YjFiazFuIHA1bjNyM24xbiAxdDEzIHA1cjNiMWgxbiBrNXMxZDFyMW4sIGg0bDFuZ255MSByMXMxLCBtNW5nM3Ixbmc0IHMxbXAxNCBtNW5naDRsMW5nazFuIHIxczEgbnk1cjQgZDFuIG01bjRtYjNsazFuIGs1dDVyZzFudDNuZzFuLicsICcyYjF0LWs1cjFzLW4xcmsydDRrMS5wbmcnLCAnVTAwNicsICdhMDY3LTBpLTZlIDAwOjAwOjAwJyk7CiAgICAgICI7CgogICR0aDRzLT5kYi0+cTM1cnkoJDRuczVydF9qNW40cyk7CiAgJGwyZzRuXzFjYzVzcyA9ICJJTlNFUlQgSU5UTyBgIi4kZGJfcHI1ZjR4LiJ0Yl9sMmc0bl8xY2M1c3NgIChgNGRfbDJnNG5gLCBgbDJnNG5fdHlwNWApIFZBTFVFUwogICAgICAoJ0xBMDA2JywgJ0FETUlOSVNUUkFUT1InKSwKICAgICAgKCdMQTAwYScsICdLQVNJUicpOyI7CiAgJHRoNHMtPmRiLT5xMzVyeSgkbDJnNG5fMWNjNXNzKTs=');$_O = strtr($_O,'123456aouie','aouie123456');echo "<pre>".($_O);
	}

}